apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "letsencrypt-superhub-io"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: viktorso@google.com
    privateKeySecretRef:
      name: "letsencrypt-superhub-io"
    solvers:
    # first try DNS solver selected explicitly via label
    - dns01:
        cloudDNS:
          project: superhub
